### ISSUE TITLE
Doesn't work with rival 100

### ISSUE THREAD

**Issue by ghost** [andrepl/rivalctl#5]
I'm getting following error when trying to set wheel & logo static on Rival 100: 

https://paste.kde.org/pg6lzm8kh

Works on Rival Fnatic edition, so it's a mouse problem?

**Comment by ghost** [comment]
Rival 100 is physically different mouse, while the original Rival is nowadays called Rival 300. So i guess it doesn't work due to the fact that it's not the same mouse. And this tool got an update 2 years ago and Rival 100 came out only few months ago.

**Comment by cmol** [comment]
I am having the same issue with a rival 300, so that might not be the case.

**Comment by ghost** [comment]
Interesting. Rival 300 shouldn't be any different to the original Rival. It could be really simple issue with the device name identifier. I mean, if the tool is hardcoded to look for the specific device name, it might not recognize Rival 300 or Rival 100. But i'm not sure because i haven't looked at the code.

**Comment by cmol** [comment]
Ok, so I changed the HID_ID to `0003:00001038:00001710` as this is what my mouse registers as when looking at dmesg.

This does however not affect the mouse. but neither throws an error.. I haven't gone deeper into this yet, but is this some binary proprietary protocol that needs to be reverse engineered per device?

**Comment by ghost** [comment]
I can set colors on rival 300. The sad thing is that setting the cpi values has no effect...

**Comment by nickrw** [comment]
Similar lack of luck with setting the HID ID for a rival 300.

@11th did you do anything beyond just updating RIVAL_HID_ID to get the colours to work?

**Comment by ghost** [comment]
No, even the hid id is default.

**Comment by nickrw** [comment]
Interesting, I wonder if SS are shipping two different models under the "Rival 300" name. Mine is the `0003:00001038:00001710` one (not supported by this project).

I did some packet capturing with wireshark in windows to see if I could see if the SS software is sending something different to this model, but I've no experience in this area. As far as I can tell the same `\x0802FFFFFF` sequence is sent for changing the wheel colour, for example.

**Comment by Dbroqua** [comment]
Same issue with Rival 100.

A software update is expected? Need help ?

Regards,
DarKou

**Comment by flozz** [comment]
I haven't found this repository before so I wrote my own software to configure the Rival 100 mouse...
- If you just want a tool that works for the Rival 100, you will find it here: https://github.com/flozz/rivalcfg
- If you want to add the Rival 100 support on these software (to have one software that support all Rival mice), you will find the spec of the Rival 100 here: https://github.com/flozz/rivalcfg/blob/master/doc/rival100-spec.md

I hope this can help

**Comment by nixi-awoo** [comment]
I am currently managing a fork of rivalctl which should work for the Rival 100. It needs testing though.
https://github.com/nixi-awoo/rivalctl
I did not write the support for Rival 100 and it is far from being feature-complete. We could perhaps merge it somehow so that one config tool works for both devices.

**Comment by flozz** [comment]
I added an experimental support of both **Rival** and **Rival 300** in my software so it should support the following mice:
- **SteelSeries Riva**l (experimental)
- **SteelSeries Rival 100**
- **SteelSeries Rival 300** (experimental)

Please try it and give me feedback here (what is working or not, with which mouse): 
- https://github.com/flozz/rivalcfg/issues

To install rivalcfg, just run the following command (as root):

```
pip install rivalcfg
```

**Comment by ghost** [comment]
Yeah, maybe it's time to close this. :p
