### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by shmink** [andrepl/rivalctl#6]
After being in the cloned directory and then using `sudo python setup.py install` I keep getting [the following traceback error](http://i.imgur.com/wzO4yrs.png).

**Comment by nixi-awoo** [comment]
You have run the setup script using python2. eg.:
`python2 setup.py install`
Make sure you have all the dependencies for python2 as well.

**Comment by shmink** [comment]
[Doesn't seem to matter.](http://i.imgur.com/fgIpYpy.png)

**Comment by nixi-awoo** [comment]
You do not have setuptools for python2 installed. Use [this package](https://aur.archlinux.org/packages/rivalctl-git) from AUR if you happen to be on ArchLinux. Otherwise install all dependencies for python2 manually.

**Comment by shmink** [comment]
It's Ubuntu but thanks friend I got installed and working.

**Comment by nixi-awoo** [comment]
No worries. You might also want to test [this fork](https://github.com/pacoqueen/rivalctl) which seems to have new features and fixes.

**Comment by shmink** [comment]
Quick question. After `rivalctl --commit` will the mouse keep the settings even after reboot? What's the fork about? What new features?

**Comment by nixi-awoo** [comment]
--commit should upload current settings to the internal memory of the mouse, so nothing should reset after a reboot. I just had a quick look at the fork and it seems to be under active development. Feel free to check the commits.

**Comment by shmink** [comment]
Will do. It's just nothing really seems that different.

EDIT: Change colour of mouse based on CPU load, sweet.
